version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php-fpm
      - db
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    restart: always
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html
    env_file:
      - .env

  db:
    image: postgres:10.1
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

#  rabbitmq:
#      image: rabbitmq:3.10.7-management
#      hostname: rabbitmq
#      restart: always
#      environment:
#          - RABBITMQ_DEFAULT_USER=rmuser
#          - RABBITMQ_DEFAULT_PASS=rmpassword
#          - RABBITMQ_DEFAULT_VHOST=/
#          - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
#      volumes:
#          - ./rabbitmq:/var/lib/rabbitmq
#      ports:
#          - 15672:15672
#          - 5672:5672
